<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRD9M8CL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRD9M8CL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRD9M8CL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRD9M8CL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRD9M8CL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RD9M8CL',
    'container.build_id' => '8976512a',
    'container.build_time' => 1651686197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRD9M8CL');
