<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSewzm8g\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSewzm8g/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSewzm8g.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSewzm8g\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSewzm8g\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Sewzm8g',
    'container.build_id' => '12314251',
    'container.build_time' => 1651019332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSewzm8g');
