<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSVx5gnF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSVx5gnF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSVx5gnF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSVx5gnF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSVx5gnF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SVx5gnF',
    'container.build_id' => '318955f4',
    'container.build_time' => 1652204638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSVx5gnF');
